apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ShehabGamal689/gitops'
    targetRevision: HEAD
    path: test-k8s-app/base
    helm:
      valueFiles:
        - ../base/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

