helm:
  parameters:
  - name: image.name
    value: 614563210494.dkr.ecr.us-east-1.amazonaws.com/test
    forcestring: true
  - name: image.tag
    value: "27"
    forcestring: true
  - name: app.image
    value: 614563210494.dkr.ecr.us-east-1.amazonaws.com/test:36
    forcestring: true
