apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-sa-token
  namespace: external-secrets
  annotations:
    kubernetes.io/service-account.name: "external-secrets-sa"
type: kubernetes.io/service-account-token
