apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
  namespace: default
spec:
  secretStoreRef:
    name: mysecretstore
    kind: ClusterSecretStore
  target:
    name: aws-secrets-extracted
  data:
    - secretKey: RDS_HOST
      remoteRef:
        key: aws-secret
        property: RDS_HOST
    - secretKey: RDS_USERNAME
      remoteRef:
        key: aws-secret
        property: RDS_USERNAME
    - secretKey: RDS_PASSWORD
      remoteRef:
        key: aws-secret
        property: RDS_PASSWORD
    - secretKey: RDS_PORT
      remoteRef:
        key: aws-secret
        property: RDS_PORT
    - secretKey: REDIS_HOST
      remoteRef:
        key: aws-secret
        property: REDIS_HOST
    - secretKey: REDIS_PORT
      remoteRef:
        key: aws-secret
        property: REDIS_PORT
