apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
spec:
  secretStoreRef:
    name: mysecretstore
    kind: SecretStore
  target:
    name: aws-secrets-extracted
  data:
    - secretKey: RDS_HOSTNAME
      remoteRef:
        key: aws-secret
        property: RDS_HOSTNAME
    - secretKey: RDS_USERNAME
      remoteRef:
        key: aws-secret
        property: RDS_USERNAME
    - secretKey: RDS_PASSWORD
      remoteRef:
        key: aws-secret
        property: RDS_PASSWORD
    - secretKey: RDS_PORT
      remoteRef:
        key: aws-secret
        property: RDS_PORT
    - secretKey: REDIS_HOSTNAME
      remoteRef:
        key: aws-secret
        property: REDIS_HOSTNAME
    - secretKey: REDIS_PORT
      remoteRef:
        key: aws-secret
        property: REDIS_PORT
