resources:
  - app-deployment.yaml
  - app-service.yaml
  - cluster-issuer.yaml
  - externalsecret.yaml
  - mysql-stateful.yaml
  - mysql-service.yaml
  - node-ingress.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - secret-store.yaml
  - service-account.yaml
  
