apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aws-secrets-extracted
              key: RDS_PASSWORD
        volumeMounts:
        - name: mysql-temp-storage
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-temp-storage
          emptyDir: {}