apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "gp-mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: gp-mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-extracted
                  key: RDS_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-extracted
                  key: RDS_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-extracted
                  key: RDS_PASSWORD
            - name: MYSQL_ROOT_HOST
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-extracted
                  key: RDS_HOST
            - name: MYSQL_INITDB_SKIP_TZINFO
              value: "1"
            - name: MYSQL_DEFAULT_AUTHENTICATION_PLUGIN
              value: "mysql_native_password"
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: aws-secrets-extracted
                  key: RDS_PORT
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: gp-mysql-pvc
