apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
      annotations:
        # Using semver to track v1.* versions
        argocd-image-updater.argoproj.io/image-list: "shebogimmy/node-app:semver:v1.*"
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: main
        argocd-image-updater.argoproj.io/update-strategy: semver
    spec:
      containers:
        - name: node-app
          # Initially set to a fixed version like v1.0.1
          image: shebogimmy/node-app:v1.0.1
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: gp-mysql
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: root
            - name: REDIS_HOST
              value: redis

