app:
  image: megs17/node_rds_redis_2:latest
  port: 3000
  nodePort: 30080

mysql:
  rootPassword: example
  storage: 1Gi

redis:
  port: 6379

secrets:
  rds_host: mysql
  rds_user: root
  rds_password: example
  rds_port: "3306"
  redis_host: redis
  redis_port: "6379"

