apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: app
        image: {{ .Values.app.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.app.port }}
        envFrom:
        - secretRef:
            name: aws-secrets-extracted
