apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: "shebogimmy/node-app:latest"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/update-strategy: tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: app
        image: {{ .Values.app.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.app.port }}
        envFrom:
        - secretRef:
            name: aws-secrets-extracted
